### ISSUE TITLE
ArrayVec is undefined behavior when storing types with invalid bit patterns

### ISSUE THREAD

**Issue by orlp** [bluss/arrayvec#105]
Initially in an `ArrayVec` the memory is uninitialized: https://github.com/bluss/arrayvec/blob/master/src/lib.rs#L80.

This simply is UB in Rust for any types with invalid bit patterns (most notably references). Just *creating* an uninitialized value with these bit patterns is UB.

Even perfectly fine code that never actually reads or uses the uninitialized memory still has undefined behavior. I ran into this myself: https://stackoverflow.com/questions/52348277/vector-is-empty-after-cloning-struct-with-uninitialized-member.

**Comment by bluss** [comment]
Thanks, this is something that has clarified a lot in recent versions of Rust, and we should be able to use MaybeUninitialized soon.

**Comment by bluss** [comment]
See also #97 and related issues and prs

**Comment by bluss** [comment]
Closed by #127 with the cavat, that Rust 1.36 or later is required.
