### ISSUE TITLE
ArrayVec from slice

### ISSUE THREAD

**Issue by cchudant** [bluss/arrayvec#106]
How can i create an ArrayVec from a slice?
There is no ArrayVec::from(&[T])

**Comment by tbu-** [comment]
`.iter().cloned().collect()` works. You might need a type hint somewhere.

**Comment by bluss** [comment]
@SkyBeastMC From is not a good fit for a fallible operation. The operation can fail, if the capacity of the arrayvec is not enough for the slice. TryFrom would be good

**Comment by bluss** [comment]
TryFrom is stable in Rust 1.34, which arrayvec requires.
