### ISSUE TITLE
Crate on crates.io doesn't contain 0.4.10 code

### ISSUE THREAD

**Issue by Thomasdezeeuw** [bluss/arrayvec#120]
According to the git history commit 233df73ab267e46d69f6cfd3e8f9131ad74d69bf should be in v0.4.10. However downloading the crate from crates.io (https://crates.io/api/v1/crates/arrayvec/0.4.10/download and extract it with `tar -xzvf arrayvec-0.4.10.crate`) shows the code before the commit. Was outdated code uploaded to crates.io?

**Comment by Thomasdezeeuw** [comment]
You can also see the outdated code on https://docs.rs/arrayvec/0.4.10/arrayvec/struct.ArrayVec.html#method.clear.

**Comment by bluss** [comment]
Hi, git history doesn't say that this commit should be in the 0.4 branch or in the 0.4.10 release.

You can ask git about which releases should contain that particular commit: git tag --contains 233df73ab267e46d69f6cfd3e8f9131ad74d69bf  (currently it is none).

**Comment by Thomasdezeeuw** [comment]
Ah, I see. I looked at the master branch which was at v0.4.10 and included the commit, so I was a bit confused.
