### ISSUE TITLE
support for no_std is broken

### ISSUE THREAD

**Issue by brenzi** [bluss/arrayvec#122]
This crate doesn't work for no_std. 
On of the reasons:
https://github.com/bluss/arrayvec/blob/fd4a6469b9505109aa8a0539dbc7d36641ce0617/src/lib.rs#L34

Any chance to get no_std support?

**Comment by burdges** [comment]
I'm surprised https://github.com/bluss/arrayvec/blob/fd4a6469b9505109aa8a0539dbc7d36641ce0617/src/lib.rs#L28-L29 does not handle this?

**Comment by brenzi** [comment]
You're right. probably the problem lies somewhere else? Maybe not even in arrayvec?
I'll have to check later

**Comment by brenzi** [comment]
wrong accusation
