### ISSUE TITLE
Default is not intuitive

### ISSUE THREAD

**Issue by Boscop** [bluss/arrayvec#134]
I assumed `default()` would create an array of len `N` and initialize all elements by calling their `Default` impl (mirroring normal arrays), but it just creates an empty `ArrayVec`.
It would make more sense to have `default()` initialize all `N` elements with their default, like this: 
```rust
ArrayVec::from(array![Default::default(); N])
```
(Using [`array-macro`](https://crates.io/crates/array-macro) here to demonstrate the desired semantics.)

**Comment by bluss** [comment]
Arrayvec is a vector with constant capacity, so everything is modelled on the Vec, where possible. Thus the default is empty.

**Comment by bluss** [comment]
I'll close this as already handled since I think the question of "is arrayvec an array or a vector?" has a clear cut answer.
