### ISSUE TITLE
ArrayString::from_raw_parts

### ISSUE THREAD

**Issue by NickeZ** [bluss/arrayvec#141]
I have a question for you!

In C-code it is quite common to have `void do_something(char* buf, size_t buf_len);`. Where you are supposed to write the result to the provided buffer, only up to `buf_len` length.

I would like to be able to write to such a buffer using `write!(buf, "Fancy formatting {}", "!");`.

Right now I write to an ArrayString and the use `core::slice::copy_from_slice(...)` to copy to a slice I've created with `core::slice::from_raw_parts_mut(...)`. But it would have been totally awesome if could have constructed an ArrayString from a raw pointer and length. Would that be possible?

Obviously I work in a `#[no_std]` environment..

**Comment by bluss** [comment]
Hallå!

First I'll have to ask if you can't just use the native Write support of `&mut [u8]` itself.

```rust
use std::io::Write;

unsafe fn do_something(buf: *mut u8, buf_len: usize) {
    let mut s = std::slice::from_raw_parts_mut(buf, buf_len);
    write!(s, "fancy formatting {}", 2.71828).unwrap();
    let remaining_length = s.len();
    println!("Remaining={}", remaining_length);
}

fn main() {
    let mut data = [0; 100];
    unsafe { do_something(data.as_mut_ptr(), data.len()); }
    println!("{:?}", std::str::from_utf8(&data));
}
```

Constucting an ArrayString from a pointer only makes sense to me if the operation that would do would be to copy data through the pointer, into a new ArrayString. Since the ArrayString stores its data inline, we can't tell it to store its data at a particular pointer.

**Comment by NickeZ** [comment]
Hej!

As far as I understand `core` doesn't have `io::Write`. So I have to use `fmt::Write` which only works with `String`, which I don't have (because of `no_std`), and ArrayString. I must stress that there might be an obvious solution that I'm overlooking because I'm not that experienced in rust yet.

Thanks!

**Comment by NickeZ** [comment]
I could construct a `String` if I bring in the `alloc` crate. But alloc is not yet available on the stable compiler. This attribute seems to be missing: https://github.com/rust-lang/rust/issues/51540

**Comment by bluss** [comment]
Oh right. So all the non-std+allcoc Work is still somewhat of a futile exercise, that's good to know.

I'd look next at core_io or similar I'd it doesn't let you do the equivalent thing as std io Write.

For ArrayString, the capacity is type level information and there is only so much we can do given a buf_len as input, you'd have to insert some logic that picks a long enough ArrayString and abstracts the varying ArrayString type.

**Comment by NickeZ** [comment]
Cool `core_io` sounds like the right thing!

**Comment by bluss** [comment]
It's not something I'll do now, but providing your own shim for this should not be impossible. See https://doc.rust-lang.org/nightly/src/std/io/mod.rs.html#1219-1448  (std::io::Write::write_fmt source), and you can simplify it by having simpler error handling.

**Comment by bluss** [comment]
Ping me if we should look closer at making a working shim for using `write!` on `&mut [u8]`
