### ISSUE TITLE
Rename `try_extend_from_slice`

### ISSUE THREAD

**Issue by piegamesde** [bluss/arrayvec#145]
I was looking for a method to push all items of a slice to an `ArrayVec`, and could not find any functions like `push_slice`. What I found though, is `try_extend_from_slice`, which basically does the job.

- This name is pretty unintuitive to me. The "extend" part in it creates the intuition that the capacity of the vector changes, which is not true. I know this method comes from its `Vec` equivalent, but it doesn't really fit for a fixed size buffer. I'd prefer `try_push_slice` as name.
- If we have a `try_push_slice` method, we should also have a `push_slice` and a `push_slice_unchecked` for orthogonality.

**Comment by bluss** [comment]
It's called extend from slice on Vec, so that is the naming precedent that is used.

**Comment by piegamesde** [comment]
I know this, but I still think the name does not fit on a fixed size buffer and I'd still like to have an unchecked version of this.

**Comment by bluss** [comment]
You have a good point, but on balance we will keep the Vec names. We also implement traits like `Extend`. We extend the length of the array, not the capacity.
