### ISSUE TITLE
CI should fail, if the code isn't rustfmted

### ISSUE THREAD

**Issue by Luro02** [bluss/arrayvec#153]
See https://github.com/rust-lang/rustfmt#checking-style-on-a-ci-server

**Comment by bluss** [comment]
This is always something that current maintainers will decide about. Presently, this does not add value.

**Comment by Luro02** [comment]
Would you mind to elaborate your statement a bit?

I think this really does add value to the project, like how miri, clippy and `cargo audit` do.

Pros:
+ more streamlined codebase (easier to read)
+ removes redundant things like an unnecessary `{}`
+ prevents git merge conflicts. For example my PR ( #151 ) will definitely cause merge conflicts with the other PRs.


Cons:
- might stop PRs, until you run `cargo fmt`, not a huge deal...
