### ISSUE TITLE
Don't care about the array size

### ISSUE THREAD

**Issue by piegamesde** [bluss/arrayvec#154]
I have a public API that needs to take in a `ArrayVec` as a fixed-size buffer. But sadly (in this case), the `ArrayVec` is not only generic over the item type, but also over its size. This means, if I (for example) want a `ArrayVec` of floats without caring about its size, I need to use a generic `<A: Array<Item=float>`, `ArrayVec<A>` everywhere. This not only makes code less readable, but also disallows dynamic trait objects if used in there.

I'd like to have the possibility to ask for an `ArrayVec<float>` without having to care for the size. I made a quick prototype using trait magic:

```rust
pub trait ArrayVecDyn<Item>: Deref<Target = [Item]> + DerefMut<Target = [Item]> {
	fn push(&mut self, element: Item);

	unsafe fn push_unchecked(&mut self, element: Item);

	fn clear(&mut self);

	fn remaining_capacity(&self) -> usize;
}

impl<A: Array> ArrayVecDyn<A::Item> for ArrayVec<A> {
	fn try_push(&mut self, element: A::Item) {
		self.push(element)
	}

	unsafe fn push_unchecked(&mut self, element: A::Item) {
		self.push_unchecked(element)
	}

	fn clear(&mut self) {
		self.clear()
	}

	fn remaining_capacity(&self) -> usize {
		self.remaining_capacity()
	}
}
```

**Comment by bluss** [comment]
It seems like you need a trait yes, maybe something that even Vec can implement. You might as well prototype this out of crate, that's more productive for you, and at this point it is unlikely we would include it in arrayvec itself, unless we have a very promising prototype.

**Comment by piegamesde** [comment]
The problem with my trait solution is that, while functional, it requires dynamic dispatch.

> maybe something that even Vec can implement

That would be amazing, but I doubt so. What I really need is a Vec-like structure, but with the guarantee that it won't re-allocate after creation. Maybe something like ArrayVec, but based on a boxed slice rather than an array.

If `Array::CAPACITY` wasn't a constant, but a function, I could implement Array for `Box<[T]>` and see if that works out.

**Comment by bluss** [comment]
I think any solution I see here requires dynamic dispatch. If you go to use a Box as backing store, then it sounds like just using `Vec` would be even better, not using arrayvec.
