### ISSUE TITLE
[Question] How can I store an ArrayVec on stack?

### ISSUE THREAD

**Issue by y-ich** [bluss/arrayvec#16]
Hi.

I want to a vec on stack.
It seems possible by your crate.
The documentation says "The vector is a contiguous value that you can store directly on the stack if needed."
How can I store an ArrayVec on stack?
"from" method?
(I could not understand the mechanism of "new" method of ArrayVec...)

**Comment by bluss** [comment]
Just put the arrayvec in a temporary:

```
let mut x = ArrayVec::<[_; 8]>::new();
x.push(1);
```

`x` is on the stack. The ArrayVec stores everything inline, so it's simple for the user to decide where to store the data.

Since a box is heap allocated the following would be an array vec that lives in the heap:

```rust
let y = Box::new(ArrayVec::from([0; 16]));
```

**Comment by y-ich** [comment]
Thank you!

**Comment by bluss** [comment]
No problem, questions are welcome!

**Comment by BrittMcDanel** [comment]
I had the same question, it wasn't clear if by default the ArrayVec is stack allocated (i.e without using Box). Thanks.
