### ISSUE TITLE
MSRV policy?

### ISSUE THREAD

**Issue by jhpratt** [bluss/arrayvec#160]
Hello. I'm looking at using arrayvec as part of no-alloc support in the time crate. What is the policy on bumping the MSRV, if there is one?

**Comment by bluss** [comment]
Doc for version is here https://docs.rs/arrayvec/0.5.1/arrayvec/#rust-version

Bumping MSRV is a breaking change in the 0.x, 0.y etc chain of releases, and when we go 1.x it will be the same as indexmap's policy: https://docs.rs/indexmap/1.3.2/indexmap/#rust-version

**Comment by jhpratt** [comment]
Perfect, thanks for the quick response!
