### ISSUE TITLE
No .dedup() method

### ISSUE THREAD

**Issue by Arifd** [bluss/arrayvec#168]
Looking for a way to dedup. tinyvec::ArrayVec has it. So I'm guessing It's possible?

Could we see this implemented any time soon?

**Comment by bluss** [comment]
PRs welcome

**Comment by Arifd** [comment]
Hi bluss, I may look into this into the future but for now just wanted to report future searchers that this crate provides an iterator adaptor to do the same thing: https://crates.io/crates/dedup_iter

**Comment by bluss** [comment]
Ok PRs welcome but no need to keep this around then :) Itertools also has a deduplicating adaptor. We note that an in-place dedup is not exactly the same.
