### ISSUE TITLE
Can I avoid memcpy?

### ISSUE THREAD

**Issue by y-ich** [bluss/arrayvec#17]
Hi.

In order to avoid allocation, I am using your ArrayVec instead of Vec. Thanks.
I could certainly avoid allocation it seems that ArrayVec consumes time by memcpy when dropping.
Type of ArrayVec is integer(u8, usize), not structs using heap, so I wonder there is no need to clean up.

Is my understanding right?
and if so, can I avoid it?

**Comment by bluss** [comment]
Ideally, I think it should be removed in optimization. Is this something you found in an optimized build?

If the `ArrayVec` is not a struct field, then you can use `std::mem::forget(array)` directly (if it is empty or the elements have no destructor).

**Comment by bluss** [comment]
It looks like the memcpy / overwrite is not optimized out properly. We can automatically skip it, but only by using a nightly / unstable feature (std::intrinsics::needs_drop), but I've added a feature flag to crate `nodrop` called `use_needs_drop` that enables this. 

To use it: Depend directly on crate `nodrop`, enable feature flag `use_needs_drop` for nodrop. To only do it temporarily you can use `--features=nodrop/use_needs_drop`.

Of course, the big memcpy is redundant (only a small part needs to be overwritten to set the flag that inhibits drop, but it's the most clean way to implement it. Maybe we can improve..

**Comment by y-ich** [comment]
Thank you for your advice.
As you mentioned, I was confused because memcpys appear in some functions and does not appear in some other functions, and now I understood as instability of optimization.

I will see std::mem::forget(array) at first.

Thank you!
