### ISSUE TITLE
Performance regression in 0.6.1

### ISSUE THREAD

**Issue by niklasf** [bluss/arrayvec#182]
https://github.com/niklasf/shakmaty/blob/master/benches/benches.rs are showing a major performance regression going from arravec 0.6.0 to 0.6.1. For example:

```
bench_shallow_perft
  Instructions:            31844284 (+153.8268%)
  L1 Accesses:             54897187 (+233.5472%)
  L2 Accesses:                  315 (+47.19626%)
  RAM Accesses:                 472 (+8.505747%)
  Estimated Cycles:        54915282 (+233.3271%)
```

I bisected it to 5ad4687b1be20707dc281fd383486c1128700a41 as the first bad commit.

The benchmarks are mostly using `ArrayVec::{new,push,retain}()`. So far I did not manage to reduce it further.

**Comment by bluss** [comment]
That's unfortunate, it's not possible to just revert that change either. More examination is needed. Would be great if it was just a matter of `#[inline]`, but potentially not(?)

**Comment by bluss** [comment]
Maybe we'll just revert new, add a new_const constructor (both stable) and publish 0.7.0.

**Comment by rodrimati1992** [comment]
The compiler is emitting code for initializing the array of MaybeUninit (even though it doesn't need to):
https://rust.godbolt.org/z/5e1o53q9a

**Comment by bluss** [comment]
Thanks

**Comment by bluss** [comment]
Because the 0.6 version was so new, it is a rather small cost to release 0.7 immediately to fix this, not so much installed base to bother with the upgrade. So thanks for flagging this so quickly, too.

**Comment by bluss** [comment]
@niklasf If you have this info, how was the performance of arrayvec 0.6.0 or 0.7.0 compared with the previous version 0.5.2, any changes?

**Comment by niklasf** [comment]
Thanks for handling this so quickly.

0.5.2 to 0.7 is a slight improvement (possibly within noise limits). For example, the benchmark that flagged this issue:

```
bench_shallow_perft
  Instructions:            12345813 (-0.052298%)
  L1 Accesses:             16236361 (-0.309209%)
  L2 Accesses:                  121 (-33.51648%)
  RAM Accesses:                 431 (-2.927928%)
  Estimated Cycles:        16252051 (-0.313559%)
```

**Comment by bluss** [comment]
Your retain improvement is also in 0.7. Release note will be updated with that.
