### ISSUE TITLE
Const generics are unstable

### ISSUE THREAD

**Issue by ivanka2012** [bluss/arrayvec#184]
On Windows 10, Ubuntu 20.04 LTS, if you run `cargo build --release`, a bunch of errors will pop out saying that `const generics are unstable`. The affected files are utils.rs, array_string.rs, arrayvec.rs

**Comment by bluss** [comment]
Hi, you need a newer compiler (see https://docs.rs/arrayvec for version info) or need to use a version of arrayvec that is compatible with the one you have - probably arrayvec 0.5.*)
