### ISSUE TITLE
Minimum Rust version supported

### ISSUE THREAD

**Issue by elpiel** [bluss/arrayvec#185]
It would be a good idea to mention what is the minimum supported Rust version.
We are having issues with our dependencies because the 0.7 version of arrayvec uses const generics, which were stabilized in Rust 1.51. Since we rely on older version of stable Rust in our Docker builds in our project and one of our dependencies uses arrayvec 0.7 the builds started failing.

![Screenshot from 2021-04-08 11-40-17](https://user-images.githubusercontent.com/8925621/113996707-187c1700-9860-11eb-8047-da2ccc0d9811.png)

**Comment by bluss** [comment]
See docs.rs/arrayvec for documentation and also the changelog.

**Comment by elpiel** [comment]
Would you mind if this information is also added to the README of the repo?

**Comment by bluss** [comment]
Current location is best, this belongs with a specific release/version, and it shows on docs.rs in the right way.
