### ISSUE TITLE
[ArrayString] Infallible constructor to fill inner array

### ISSUE THREAD

**Issue by c410-f3r** [bluss/arrayvec#196]
Some libraries like `hex` or `bs58` expect a pre-filled buffer to operate on but `ArrayString` does not have an infallible constructor to create a fully filled inner array with "whatever".

For example, the following made use of `from_byte_string` to make everything work as expected:

```rust
let mut buffer = ArrayString::from_byte_string(&[b' '; SOME_LEN]).unwrap();
let len = bs58::encode(some_data).into(&mut buffer[..]).unwrap_or_default();
buffer.truncate(len);
```

So do you mind me providing a PR to create something like `ArrayString::new_filled()`?

**Comment by c410-f3r** [comment]
Taking into consideration that ASCII is compatible with UTF-8 and the standard library supports `u8 -> char` conversions (`ArrayString::from_byte(u8)` constructor), it is also possible to create an `ArrayString::from_ascii(byte: u8)` constructor.

**Comment by bluss** [comment]
from_ascii is not the perfect name if u8 (and the whole 0..=255 value range) is accepted.

But something like this sounds useful. Consider if `from_byte` or `new_full` or something like that would be a good name. Or even new with zeros..

**Comment by c410-f3r** [comment]
Thank you very much, @bluss!

**Comment by c410-f3r** [comment]
With my little understanding, I think that if non-printable characters are accepted as valid `char` and therefore, valid UTF-8, then a constructor that takes an arbitrary byte to fill the inner array should be acceptable.

In any case, it is just an idea. The key feature here is provide a constructor for a fully filled `ArrayString` so the contents shouldn't matter.

**Comment by bluss** [comment]
Note that any u8 value > 127 is interpreted as the codepoint of that value (128..=255) and codepoints in that range are encoded with two bytes per codepoint in UTF-8. Hence the need for bounds checking :)

**Comment by c410-f3r** [comment]
> Note that any u8 value > 127 is interpreted as the codepoint of that value (128..=255) and codepoints in that range are encoded with two bytes per codepoint in UTF-8. Hence the need for bounds checking :)

Jeez... Sorry, my bad.

Another approach could be something leveraged from arithmetic operations:

```rust
/// Negative numbers will be turned into positives
ArrayString::from_absolute_byte(byte: i8) -> Self;

/// Values greater than 127 are capped
ArrayString::from_saturating_byte(byte: u8) -> Self;

/// Actual value will be `byte % 128`
ArrayString::from_wrapping_byte(byte: u8) -> Self;

// The above methods can also be generalized to array inputs but it will require some processing.
```

Honestly, I would humble thank you if any infallible constructor that fills the inner capacity can be included in the library :)

**Comment by bluss** [comment]
I offer `ArrayString::zero_filled() -> Self` then, the simplest and easiest

**Comment by c410-f3r** [comment]
Yeah! I will provide a PR ASAP.

Thank you very much for your consideration, @bluss. Not every library author is interested in allowing a change or addition, that is why I really, really appreciate your patient, help and willingness.

**Comment by bluss** [comment]
Good. Well that kind of maintainer is often me, quite reluctant to accept stuff. This is cool and useful though.

**Comment by c410-f3r** [comment]
Hehehehe :)
Guess it is my lucky day
