### ISSUE TITLE
Additional array sizes

### ISSUE THREAD

**Issue by bluss** [bluss/arrayvec#2]
We can add arbitrary requested array sizes, if you need a lot of them they may be feature gated to not bloat the crate's default size too much, but ask away here!

So feel free to request sizes here; of course at some point in Rust's future we will have generics to cover this, and this kind of issue will be over!

**Comment by tbu-** [comment]
I'm interesting in 2**16 (65536).

**Comment by bluss** [comment]
That should be problem free to add.

**Comment by bluss** [comment]
Well if one is nitty gritty one can see problems in every corner of course. It assumes that usize is 32-bit :wink:

**Comment by bluss** [comment]
65536 is in arrayvec 0.3.22 (on branch 0.3, master is preparing for next version)

**Comment by tbu-** [comment]
Thanks!

**Comment by daboross** [comment]
It's a bit of a niche use case, but I would use `50`. I can just use the generic-array crate/feature though for the time being, but if it was added that'd be awesome!

**Comment by bluss** [comment]
use_generic_array has in fact been removed in 0.4. I noticed we were slipping their versions quite a lot -- and we could not carry a public dependency like that. All things considered it was a minor feature, and we were many versions behind when it was removed.

**Comment by michaelkourlas** [comment]
Would it be possible to use a macro that takes an array size and produces an implementation of Array for that size? That way we wouldn't need to ask you for particular array sizes; we could just add them ourselves.

**Comment by bluss** [comment]
Not possible unfortunately, needs to be in the same crate as the Array trait itself.

Maybe there's a workaround for that? Using some awkward wrapper type or similar.

**Comment by tbu-** [comment]
@bluss So, we will have generics for arbitrary impls of `Array` soon. This would mean that we have to drop the size optimization of the `length` field in `ArrayVec`. What will we do here?

**Comment by bluss** [comment]
@tbu- Yes I was just thinking about that, and it may well be the case -- I'm unsure of what we can do about that. Associated type specialization is very much in doubt as a feature (that specific part of specialization), so that can't save us either way.

If we have to choose, I think we'd like to embrace const generics either way, even if we have to use usize?

Maybe there would be some kind of solution using marker types or whatever?

**Comment by tbu-** [comment]
Well, we could make the desired index size a parameter as well.

I don't think we need `usize` for indices, `u32` is probably enough (larger than 4gb arrays on the stack don't sound like a good idea). Maybe we could even switch to `u16` by default?

**Comment by bluss** [comment]
Right. ArrayVecs are not always on the stack! They just store their contents inline, in their value. [bmap](https://github.com/bluss/bmap) is a b-tree map that's using ArrayVecs for the keys and values in each Box-allocated node.

**Comment by bluss** [comment]
I think the index parameter idea is good, though.

**Comment by michael-p** [comment]
`impl Array` for size 300 would be great!

Thank you very much!

**Comment by bluss** [comment]
Sure, sorry that I have forgotten to follow up on this.  Pull requests that add new sizes are welcome. New sizes should be under a crate feature flag.

**Comment by viper6277** [comment]
> I'm interested in an impl of Array for Index=u8 with len=36.
> 
> Thx in advance :)

I second this request... especially for UUID's

**Comment by bluss** [comment]
@viper6277 it already exists under a feature flag

**Comment by bluss** [comment]
Fixed by #172
