### ISSUE TITLE
Issues from Fuchsia review

### ISSUE THREAD

**Issue by joshlf** [bluss/arrayvec#203]
Hi there! We're interested in using `arrayvec` in Fuchsia, and as part of our review of vendoring the crate, some of our reviewers identified some issues that could be improved. It doesn't look like anything will prevent us from using `arrayvec` as-is, but hopefully you'll find these observations helpful!

The review is [here](https://fuchsia-review.googlesource.com/c/fuchsia/+/591421). If you scroll down, you'll see a list of changed files, some of which have comments on them. You can expand each file to see its comments. Let me know if you have any trouble navigating the UI!

cc @anp @tmandry

**Comment by bluss** [comment]
Thanks! Seems to be mostly comments would be nice and then the question about encode_utf8, which makes sense. The question of how to make an array of MaybeUninit, well that's already rust canon, in the docs as you note.

The safe and stable counterpart to `encode_utf8` is here in the std: https://doc.rust-lang.org/nightly/std/primitive.char.html#method.encode_utf8. Historically arrayvec was written to be very `panic`-averse, but things have changed now. I think that's another explanation for our encode_utf8.

Either way, all of the things are "would be nice" level - and the canonical filing for that is that PR would be nice, too, right? :slightly_smiling_face:
