### ISSUE TITLE
Consider `#[track_caller]` on functions that panic

### ISSUE THREAD

**Issue by joshtriplett** [bluss/arrayvec#212]
For functions that panic, such as `extend`, please consider using `#[track_caller]`, to provide more meaningful location information for debugging such panics.

(This report inspired by debugging an ArrayVec panic inside rust-lang/rust CI.)

**Comment by bluss** [comment]
Needs knowledge about the performance impact - probably not a great concern for extend, but for other hotter methods.

**Comment by joshtriplett** [comment]
@bluss Absolutely. I filed this issue rather than submitting a PR, because this would absolutely require checking the performance impact.

**Comment by bluss** [comment]
Fixed by #236
