### ISSUE TITLE
Why are inherent associated functions of `ArrayVec` implemented via calls to trait-associated functions of `ArrayVecImpl` and not vice versa?

### ISSUE THREAD

**Issue by JohnScience** [bluss/arrayvec#228]
[Example](https://github.com/bluss/arrayvec/blob/a4690c9389d5aeefffdb799ed3daa8a97597fb40/src/arrayvec.rs#L689-L692):

```rust
/// Return a mutable slice containing all elements of the vector.
pub fn as_mut_slice(&mut self) -> &mut [T] {
    ArrayVecImpl::as_mut_slice(self)
}
```

AFAIK, [const trait implementation](https://github.com/rust-lang/rust/issues/24111) is not landing soon. If [ArrayVecImpl::as_mut_slice](https://github.com/bluss/arrayvec/blob/a4690c9389d5aeefffdb799ed3daa8a97597fb40/src/arrayvec_impl.rs#L25-L30) is defined via the call to the inherent function instead (i.e. if we reverse the implementation dependency), it will be possible to have easier feature-gated support for the const inherent associated function. Instead of the dependence on both [`const_trait_impl`](https://doc.rust-lang.org/beta/unstable-book/language-features/const-trait-impl.html) and [`const_mut_refs`](https://doc.rust-lang.org/beta/unstable-book/language-features/const-mut-refs.html) features there will be the dependency only on the latter.

I guess it may be fine if you don't want to offer a feature-gated support for nightly [`const_mut_refs`](https://doc.rust-lang.org/beta/unstable-book/language-features/const-mut-refs.html). However, I wouldn't mind to help you with reversing the dependency and opt-in support for the aforementioned nightly features. There's a popular crate [`const_fn`](https://crates.io/crates/const_fn) that can help provide such support cleaner.

**Comment by bluss** [comment]
The idea for ArrayVecImpl is to pool common code - common to ArrayVec and ArrayVecCopy (when that exists), I don't think you can reverse this
