### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by Dushistov** [bluss/arrayvec#239]
Looks like several months no new commit, need any help to maintain repo?

**Comment by AngelicosPhosphoros** [comment]
@bluss Hi!
I see that you merged stacked borrows violations.
May you please publish a new update to crates.io?

**Comment by bluss** [comment]
@AngelicosPhosphoros Thanks for the ping, will do

**Comment by AngelicosPhosphoros** [comment]
Thanks!

**Comment by bluss** [comment]
As always, it's doubtful - someone more is needed for the bus factor - but will close for now.

**Comment by tbu-** [comment]
> someone more is needed for the bus factor - but will close for now.

I'd be interested in working more on this project again. I still seem to have rights to this repository, but I don't know if you still know this. Would you be okay with me merging PRs, @bluss?

**Comment by bluss** [comment]
@tbu- Thanks for the ping, yes, sure, that's welcome. Current plan is a small 0.7.5 release, so we can't merge anything breaking before that's done. If you trust yourself and don't feel like you need feedback, feel free to merge stuff yourself, also your own changes.  We could enable discussions here or you could find me in some discord project if you want to discuss something.
