### ISSUE TITLE
Better memory layout by moving len before xs

### ISSUE THREAD

**Issue by JakkuSakura** [bluss/arrayvec#254]
Hi, I noticed that `len` is arranged after `xs`
```rust
pub struct ArrayVec<T, const CAP: usize> {
    // the `len` first elements of the array are initialized
    xs: [MaybeUninit<T>; CAP],
    len: LenUint,
}
```
In C's world, it's a convention to move length before an array, like
```rust
#[repr(C)]
pub struct ArrayVec<T, const CAP: usize> {
    len: LenUint,
    // the `len` first elements of the array are initialized
    xs: [MaybeUninit<T>; CAP]
}
```
This provides a few nice features:
- better locality. First, read the length, then read the element one by one. This should be trivial though
- Easier to implement tail arrays if were to put on the heap 
- https://github.com/antirez/sds Simply Dynamic String uses a similar layout

**Comment by JakkuSakura** [comment]
sure, I'll make len type a generic parameter with default type

I'll also add a reference type to ArrayVec

**Comment by YuhanLiin** [comment]
The ordering of fields in the default representation (`repr(rust)`) is unspecified, so the length field might already be ordered before the data. Of course this depends on the compiler's discretion.
