### ISSUE TITLE
Can't build arrayvec 0.7.5 - unresolved import `std::path` (for no std)

### ISSUE THREAD

**Issue by abdallahalsamman** [bluss/arrayvec#273]
error[E0432]: unresolved import `std::path`
 --> C:\Users\evex\.cargo\registry\src\index.crates.io-6f17d22bba15001f\arrayvec-0.7.5\src\array_string.rs:8:10
  |
8 | use std::path::Path;
  |          ^^^^ could not find `path` in `std`

**Comment by bluss** [comment]
Thanks for reporting. Which rust platform and rust version?

**Comment by IvanUkhov** [comment]
It fails for me on the latest Ubuntu runner by GitHub, for instance.

**Comment by bluss** [comment]
ok, it's no-std, I can see that now. It doesn't have a test in CI apparently.

**Comment by thejpster** [comment]
Will there be a 0.7.6 with this fix? Will 0.7.5 be yanked for being a breaking change for no_std users?

**Comment by bluss** [comment]
0.7.6 is released now

**Comment by thejpster** [comment]
amazingly fast work. Thank you.

**Comment by bluss** [comment]
Well, scary how fast multiple people noticed something broke. At least good that we now have CI coverage here for that facet (no-std)..

**Comment by thejpster** [comment]
Consider yourself a small, unpaid, peg in a very large and stack.
