### ISSUE TITLE
Why are the methods of `Array` trait hidden?

### ISSUE THREAD

**Issue by johncf** [bluss/arrayvec#56]
Are [they](https://github.com/bluss/arrayvec/blob/master/src/array.rs#L6-L14) marked with `#[doc(hidden)]` to consider them "unstable"?

I have a use-case in which using `capacity` would be _very_ handy.

**Comment by bluss** [comment]
More or less, they are undocumented. I would prefer if Array was just an implementation detail. The crate is old now, so it shouldn't matter much if we expose it. Capacity is only needed for zero size type elements. Otherwise it's simply available with size of gymnastics :smile:

**Comment by johncf** [comment]
> Otherwise it's simply available with size of gymnastics :smile: 

In the depths of abstractness, those details could get lost so easily! This presented itself as a nice rope to hold on to to maintain sanity... :smile: 

I'll provide the details once I implement what I have in mind in my new crate.

**Comment by johncf** [comment]
I'll close this for now, but if it becomes crucial for not over-complicating things, I'll send a PR to make sure at least `capacity` is considered stable.
