### ISSUE TITLE
Add support for `into_inner_unchecked`

### ISSUE THREAD

**Issue by L117** [bluss/arrayvec#60]

**Comment by tbu-** [comment]
What is the motivation for this function? There is `into_inner().unwrap()` to assert the condition at runtime and there is [`into_inner().unchecked_unwrap_ok()`](https://docs.rs/unreachable/1.0.0/unreachable/trait.UncheckedResultExt.html#tymethod.unchecked_unwrap_ok) for unchecked access.

**Comment by L117** [comment]
The motivation was that Option::unwrap requires Debug trait bound which is unnecessary as unwrapping in my case always succeeds. Thanks for pointing me to `unreachable` crate, that did the trick.

**Comment by tbu-** [comment]
`Result::unwrap` has a `E: Debug` bound on the error case, but you can use `.ok().unwrap()` if your struct doesn't implement `Debug`.

**Comment by tbu-** [comment]
(This way, you don't need `unsafe` code.)
