### ISSUE TITLE
Use ManuallyDrop

### ISSUE THREAD

**Issue by bluss** [bluss/arrayvec#62]
ManuallyDrop is stable in Rust 1.20 (not yet released).

This is the official nodrop that arrayvec has been waiting a long time for; it's likely that we will use Rust 1.20 as the new required version from this point.

**Comment by bluss** [comment]
Consider using version_check which is small enough to be worth it(?)

**Comment by tbu-** [comment]
This can only get the version at runtime – do you want to add a build script?

**Comment by bluss** [comment]
Yep, exactly.

Example https://github.com/bluss/debugit/blob/master/build.rs (this one is checking nightly and not the version..)

**Comment by bluss** [comment]
We can handle this without breaks, as long as the minimum rust version is reasonable (not 1.2).

However, the question of uninit data inside manuallydrop is unresolved, so we can't really start to use it without including other workarounds too.

**Comment by niklasf** [comment]
Looks like f33c4e44ddf3a0fb87d0308362135ded9e5de91f snuck in ManuallyDrop if the `use_union` feature is set 🎉

Is there anything left to do, besides version detection, before it can entirely replace nodrop?

**Comment by bluss** [comment]
sigh, that was not intended :(

**Comment by bluss** [comment]
It's fine to use ManuallyDrop for use_union. What remains for arrayvec 1.0 is to answer the question about uninitialized data in ManuallyDrop. There was some disagreement in #rustc.

**Comment by bluss** [comment]
Thanks for pointing out that it snuck in, by the way. It was obviously not intended to sneak in.

**Comment by tbu-** [comment]
Can you link to the discussion about uninit data in `ManuallyDrop`?

**Comment by bluss** [comment]
The discussion is here: https://botbot.me/mozilla/rustc/2017-08-24/?msg=90238011&page=3

There are different opinions. I don't think specific people are wrong here, but my collected impression was that there is no consensus on the safety of uninitialized in ManuallyDrop

**Comment by tbu-** [comment]
Your idea of making a union `union MaybeInitialized<T>{ t: T, uninit: () }` sounds good and forward-compatible if the `O(n)` cost gets optimized out by the compiler.

**Comment by bluss** [comment]
Current wip is #76

**Comment by bluss** [comment]
Closed in favour of #118
