### ISSUE TITLE
ArrayString lacks removal features

### ISSUE THREAD

**Issue by james-darkfox** [bluss/arrayvec#66]
`ArrayString` lacks any removal features. `pop` `truncate` `remove` etc would be nice.

All of these may be copied from `std::String` AFAIK.

I will implement these and more if requested. I've opened this issue to discuss because this seems too obvious to have been accidentally omitted?

**Comment by tbu-** [comment]
These are not omitted on purpose.

**Comment by james-darkfox** [comment]
@tbu- I would expect not. I'll implement this "soon (tm)" unless someone beats me to it.

**Comment by bluss** [comment]
Mentoring instructions: PRs are welcome.

- Focus on mimicking existing `String` methods in their complete API (equal signature is preferred) and in docs (adapted appropriately).
- Ask me on rust channels on mozilla IRC if you want
