### ISSUE TITLE
Remove dependency on odds crate

### ISSUE THREAD

**Issue by clarcharr** [bluss/arrayvec#73]
The only reference to this crate is via the `encode_utf8` function, which is now part of the standard library. IMHO it'd be better to use the stdlib version instead of that one.

**Comment by bluss** [comment]
Makes sense when it's removed from nodrop too.

**Comment by bluss** [comment]
Man, that odds thing really needs a good spring cleaning.  In nodrop we only use its debug_assert_unreachable, and the annoying thing is that `std::mem::unreachable` (whatever its final name is going to be) is still unstable, and the crate unreachable depends on another micro crate void. Which is much smaller than odds, but still annoying :-)

**Comment by clarcharr** [comment]
IMHO a lot of the things in odds should be separated into other crates or just sent upstream. It's kind of ridiculous.

**Comment by bluss** [comment]
Yes I agree of course. It's partly happening in its master branch, but there's a bit much to clean up.

**Comment by bluss** [comment]
Odds is showing signs of Rust gaining features, it contains obsolete versions of Vec::splice, std::ptr::eq, str::repeat and some more things

**Comment by bluss** [comment]
arrayvec 0.4.3 depends on odds *without* std, which might save thenths of seconds of compile time.

**Comment by bluss** [comment]
Nevermind nodrop puts that std back 🤦‍♂️
