### ISSUE TITLE
update docs around use_union

### ISSUE THREAD

**Issue by oconnor663** [bluss/arrayvec#86]
The docs still say that `use_union` requires the nightly channel, but it looks like it no longer does? (Though it also sounds like there are some [safety questions](https://github.com/bluss/arrayvec/issues/62) still open?)

**Comment by bluss** [comment]
Yes, the mishap with going over to ManuallyDrop there was a bit unfortunate. It's a good idea to put it on a bit safer ground (aligning a bit with the experimental PR). I don't want to update the docs; it's an experimental / unstable feature in arrayvec.

Good course of action would be to nullify the feature (make it a no op) and introduce a new one.

**Comment by bluss** [comment]
Closed by #114
