### ISSUE TITLE
Support for other collections

### ISSUE THREAD

**Issue by CryZe** [bluss/arrayvec#89]
Yesterday I had the need for ArrayVecDeque and today I need one for HashSet. So maybe it makes sense to have ArrayVec versions of all / most of the collections. Maybe just ArrayVecDeque if the other collections are too out of scope for this crate.

**Comment by bluss** [comment]
arraydeque already exists in a separate crate. I've also heard that servo has a cool LruCache based on arrayvec.. I'd encourage new data structures to be implemented in separate crates! If you want to share types (like the Array trait), bring the proposal and we'll do it.

**Comment by bluss** [comment]
They are all out of scope for this crate. I'm open to collaborating on shared internals (new low level functionality in ArrayVec).
