### ISSUE TITLE
Consider replicating the `Vec` interface more closely

### ISSUE THREAD

**Issue by tbu-** [bluss/arrayvec#9]
I'm specifically talking about the `remove` and `swap_remove` methods, they both return `T` in `Vec` (panic if out of bounds), whereas this one returns `Some(T)` and `None` if out of bounds.

Another nit is that `push` returns an `Option` instead of a `Result`, so you can't use `try!` together with that. My suggestion would be to return an `Result<(),ArrayVecFull<T>>`, with an `into_inner` method for `ArrayVecFull<T>`.

I'd prepare a pull request if you'd like these changes.

**Comment by bluss** [comment]
It's sad to have to add more panic cases into the library. Not a huge fan of that.

**Comment by tbu-** [comment]
It's what the standard library does and I'd like to use `arrayvec` as an almost drop-in replacement.

Short of panicking, my next preferred method would be to return a `Result` so errors in `remove` and `swap_remove` would at least not hide silently.

**Comment by bluss** [comment]
I'll think about it. I don't consider push and remove to have errors.

Methods affected:

- push
- remove
- swap_remove
- insert

**Comment by tbu-** [comment]
(It could be considered as a lack of capacity – however returning an error does not mean that the user must treat it as such, just that they are reminded that the `push` method might also *not* modify the collection and that they should take appropiate action, e.g. by just ignoring it.)

**Comment by bluss** [comment]
From discussion in #13, it looks like we are not trying to replicate Vec's signatures exactly.

**Comment by tbu-** [comment]
You're right, in my opinion, capacity-related errors should `Result`s.

The other part of this issue was that `arrayvec` modifies the semantics of `remove` and `swap_remove` – the standard library's `Vec` considers out-of-range indices a programmer error (and panics) and `arrayvec` treats these out-of-range errors as part of the normal program flow (and uses `Option`).

**Comment by bluss** [comment]
Needs new issue, the concern in this issue is obsoleted (we agreed to not replicate the Vec interface)
