### ISSUE TITLE
[wild] make ArrayVec::push take &self instead of &mut self

### ISSUE THREAD

**Issue by gnzlbg** [bluss/arrayvec#92]
There was a brief discussion about this on IRC. While doing so might be sound, it also will probably be weird.

I am just filling in this issue so that the IRC discussion can continue offline, even though this is probably only a mental exercise. 

pinging: @nox @bluss

**Comment by bluss** [comment]
First things first, so that you can take this into account; if ArrayVec should have interior mutability, it must use [`UnsafeCell`](https://doc.rust-lang.org/nightly/core/cell/struct.UnsafeCell.html) (or things using it, like `Cell`). For example, we cannot modify the length field in an ArrayVec's `&self` method unless we have interior mutability for that field.

**Comment by talchas** [comment]
In addition, you probably don't want to try making it Sync (you'd probably need two atomics, and slices would still be sync/send+copy), or support placement new on &self (also would I think need two usizes for length, and it's not like it's currently supported anyways). `(NoDrop<UnsafeCell<A>>, Cell<A::Index>)` seems like the obvious type.

**Comment by gnzlbg** [comment]
@bluss I think making the `len` field a `Cell` or `UnsafeCell` is "doable", however, @talchas point is a tougher issue, an `ArrayVec` implementation can't be `Sync` unless the len field is made an `AtomicUsize`. 

> (you'd probably need two atomics, and slices would still be sync/send+copy)

@talchas why do we need two atomics here? the capacity is fixed and `ArrayVec` can't reallocate, so the only thing that can be modified concurrently by different threads using `ArrayVec::push(&self)` is the `len` field. Or what am I missing?

**Comment by gnzlbg** [comment]
> Or what am I missing?

Duh,  on push two threads will want to bump the length _and_ add a new element to the vector, and both operations must happen atomically.

I guess that the resulting type couldn't be `Sync` then.

**Comment by bluss** [comment]
I think it is clear something that implements this would be a different, separate data structure impl from ArrayVec.

**Comment by gnzlbg** [comment]
Yes, thanks for the discussion. I didn't consider `Sync` when thinking about this.
