### ISSUE TITLE
Moving `ArrayVec`s has complexity O(capacity()) instead of O(len())

### ISSUE THREAD

**Issue by gnzlbg** [bluss/arrayvec#94]
The title says it all: moving an `ArrayVec` has complexity `O(capacity())` instead of `O(len())`. This is pretty bad.

It is trivial to construct examples that show a massive slowdown (100x's slower) with respect to C++'s `boost::container::static_vector`.

For example, moving an empty `ArrayVec<[u64; 512]>` involves `memcpy`ing 4104 bytes instead of just 8 bytes (the size of `len`). That's 513x more expensive than C++'s `boost::container::static_vector`.

**Comment by clarcharr** [comment]
I don't see a way of improving this, short of specialising `clone_from` and suggesting to use that. I'd pose this problem to the Rust upstream repo and not here.

**Comment by bluss** [comment]
@gnzlbg This seems to be a language-level (Rust) issue, and not arrayvec? As you know, we can't redefine how a value moves.

**Comment by bluss** [comment]
(clone_from is already implemented: https://docs.rs/arrayvec/0.4.7/src/arrayvec/lib.rs.html#893-913 )

**Comment by bluss** [comment]
closed, in Rust we can't change how values of a type move. I would be interested in language-level discussion about what can be done about this.

My suggestion for a workaround is to use a big arrayvec behind a pointer if you need to pass ownership of it around.
